### ISSUE TITLE
Update chain-agnostic tutorial based on feedback

### ISSUE THREAD

**Issue by maoueh** [streamingfast/substreams#100]

**Comment by seanmooretechwriter** [comment]
This is feedback from Slack from Alex for the content that was on the chain-agnostic tutorial page, now moved to Quickstart. The one thing I feel compelled to mention is that in the past, working with editors from the larger publications, using a third-person narrative for technical writing has always been required. I'm happy to make the changes, but I wanted to mention this as it's somewhat of an industry standard. At least in my experience. Here is some info I found on the web talking about it a little bit.

https://engineering.usu.edu/students/ewc/writing-resources/technical-writing-standards#:~:text=Narration%20(Point%20of%20View)&text=Third%20person%20narration%20is%20most,(common%20in%20business%20correspondence)
--------------------------------------------

Quickstart page:
Turn this page into the simplest, copy&pastable experience as possible.
The less text as possible, only the nuggets you need to continue experiencing the thing, copy & paste, with links to the docs section to learn more.
No explanation of why things are such, no explanation of 3rd-party technology.
We’d use Ethereum only where we absolutely need to have a concrete example (like pb::eth::Block (a Hint box would say: For example, on Solana, you would change pb::eth::Block to pb::sol::Block)
The Quickstart page would have the code for everything, and wouldn’t rely on you pulling a repository of code. The repository would exist as a simple link at the end: See this repository with the result of this Quickstart guide. In there, we could have slightly more comments, etc..
No comments inside code blocks, just the bare bones code.
As a general comment: “Substreams developer” to be changed to “You” everywhere it appears.

**Comment by seanmooretechwriter** [comment]
Hey Alex,

I believe this has been addressed in the latest changes you made and the style guide conformance tasks I've been working on.

Can you please let me know if it's ok to close this one out?

Thank you.
