### ISSUE TITLE
Substreams Sink Postgres tutorial

### ISSUE THREAD

**Issue by maoueh** [streamingfast/substreams#107]
We had content in the initial `Sink` documentation about `Substeams Sink Databases`, we should bring it back. It should give general database consumptions guidelines (the expected output format is the same between Postgres and mongodb for example). Most of the concepts are the same.

The tutorial should give clear information on how one can take a Substreams and transform it so it's consumable by Postgres. This is a more advanced tutorial, so we give quick overview of the commands with quick explanation. We give instructions from zero to hero. There should be validation instructions at the end (some SQL queries mainly) to ensure everything is working as expected. 

Here a first draft outline:
- Overview (discuss about transformation required to fit expected model, that the sink consumes this and populate a database.)
- Prepare your Substreams (how to respect database changes format, examples and explanations, how to check https://github.com/streamingfast/substreams-eth-block-meta for examples of the format).
- Dependencies requires (Docker compose to launch a local Postgres instance, schema population)
- Run and configure `substreams-sink-postgres` (launching, flags, output, inspect, results)
    - Discussion about where Substreams cursor is saved (in a table)
    - Discussion about batching of writes (each 1000 blocks when not live, still need to be determined when we will be live)
- Conclusion

**Comment by seanmooretechwriter** [comment]
The final outline and approach used for the files-sink tutorial should be followed for this documentation. Refer to the following link to find content and the process for creating that page/doc.

https://github.com/streamingfast/substreams/pull/116

**Comment by seanmooretechwriter** [comment]
Initial content started and draft created. New branch made for PR available at: https://github.com/streamingfast/substreams/pull/147
