### ISSUE TITLE
Substreams to `graph-node` tutorial

### ISSUE THREAD

**Issue by maoueh** [streamingfast/substreams#109]
This will be like https://github.com/streamingfast/substreams/issues/107 but for `graph-node`. The output format is really similar to database changes required by Postgres/MongoDB but tailored made for `graph-node` consumption.

Outline should be really similar, main difference is that we will **not** show how to properly start `graph-node`. We will instead have an important mentioning that for now, a development version of `graph-node` is required and this is still an on-going work in progress (the `graph-node` consuming Substreams part).

**Comment by seanmooretechwriter** [comment]
The final outline and approach used for the files-sink tutorial should be followed for this documentation. Refer to the following link to find content and the process for creating that page/doc.

https://github.com/streamingfast/substreams/pull/116
