### ISSUE TITLE
Substreams: Aggregation

### ISSUE THREAD

**Issue by maoueh** [streamingfast/substreams#133]
We need a page to explain, even if just in summary form, how to do aggregations.
Someone was using append, and that’s not the pattern. We have examples in Uniswap-v3, and we need to give a high-level overview of how to use keys to do such aggregations.

https://github.com/streamingfast/substreams-uniswap-v3/blob/develop/substreams.yaml

people are going to look how to do Aggregations, so I’d have something like “Aggregation” .. under some Tutorials or Cookbook section.. unsure where to put it right now

**Comment by fubhy** [comment]
I was experimenting with `Append` this weekend. ... :)
