### ISSUE TITLE
Solana Block Missing message field

### ISSUE THREAD

**Issue by dmelotik** [streamingfast/substreams#144]
Solana firehose protobuf defines a few fields in the `TransactionStatusMeta` that are not autogenerated in the substreams build.rs file.

Those fields are:
- [`loaded_writeable_addresses`](https://github.com/streamingfast/firehose-solana/blob/develop/proto/sf/solana/type/v1/type.proto#L65)
- [`loaded_readable_addresses`](https://github.com/streamingfast/firehose-solana/blob/develop/proto/sf/solana/type/v1/type.proto#L66)
- [`address_table_lookups`](https://github.com/streamingfast/firehose-solana/blob/develop/proto/sf/solana/type/v1/type.proto#L38)
- [`program_id`](https://github.com/streamingfast/firehose-solana/blob/develop/proto/sf/solana/type/v1/type.proto#L96)

**Comment by Eduard-Voiculescu** [comment]
Hi @dmelotik, 

The fields `address_table_lookups` and `program_id` are not part of the `TransactionStatusMeta` proto message. You can check [here](https://github.com/streamingfast/firehose-solana/blob/develop/proto/sf/solana/type/v1/type.proto#L53-L74).

Also, the fields for `loaded_writeable_addresses` and `loaded_readable_addresses` were added after the `spkg` containing  the block was generated. The `spkg` was generated on [June 3](https://github.com/streamingfast/firehose-solana/releases/tag/v0.1.0) and the proto was updated on [Sept 29th](https://github.com/streamingfast/firehose-solana/commit/eee89e5edc334008e9475308ad76a81e077a7d1f)

**Comment by dmelotik** [comment]
Hi @Eduard-Voiculescu thanks for the response! That was a mistake, `address_table_lookup` is in the `Message` and `program_id` is in `TokenBalance`. Either way it is the same issue.

What is the timeline on being able to get these in the firehose solana stream?

**Comment by dmelotik** [comment]
Thanks @Eduard-Voiculescu !

**Comment by abourget** [comment]
@jubeless was our data plucker from bigtable not updated to the latest .proto perhaps? We could rerun and overwrite some of the blocks that don't have the latest data. Let's discuss.
