### ISSUE TITLE
Investigate slow module instantiation in wasmtime

### ISSUE THREAD

**Issue by sduchesneau** [streamingfast/substreams#148]
* NewModule is called 1 time per module (ex: uniswap currently has 41 modules)
* Each time NewModule() is called, 180ms is spent (total of 6 seconds of wait time on uniswap)
* If NewModule is called concurrently on 41 modules, the first call to return will happen in ~6 seconds, and they all return together (concurrent lock ?) and the CPU is maxed out during those seconds.
* On a heavy substreams-tier2 instance, sometimes a single NewModule call will take 21 seconds to complete (if it happens at the same time as a lot of other calls ...)

Why is it so slow ? can it be improved ?

https://github.com/bytecodealliance/wasmtime-go/blob/main/module.go#L33 <---- where it blocks

**Comment by sduchesneau** [comment]
After upgrading to wasmtime v4.0.0, this issue is less significant: 75ms per module (instead of 180ms), total of 3secs. When done in parallel, 2.56 seconds before the first one completes. More manageable IMHO.

**Comment by maoueh** [comment]
@sduchesneau Can we close thise?

**Comment by sduchesneau** [comment]
close this for now, no easy improvement was found.
