### ISSUE TITLE
Substream is stuck in production mode

### ISSUE THREAD

**Issue by let4be** [streamingfast/substreams#154]
Hello!
I'm having trouble getting any data from substream in production mode while it works perfectly in development

```
substreams run -p -e localhost:9000 \
      substreams.yaml \
      db_out \
      --start-block 0 \
      --stop-block 10 \
      -o TUI --production-mode
```

produces output
```
Connected (trace ID e53da2af775e23d4277d398edd59c516)
Progress messages received: 7 (1/sec)
Backprocessing history up to requested target block 0:
```
which is forever stuck, no data, no EOF

if I remove `--production-mode` arg everything works perfectly

https://github.com/streamingfast/substreams-sink-postgres appears to be broken as well, because is_production=true is hardcoded into this tool

**Comment by let4be** [comment]
Could be the same as https://github.com/streamingfast/substreams/issues/152
because I also use store and map modules

**Comment by let4be** [comment]
Just checked, mine is broken even with a simple map when no store is defined

**Comment by maoueh** [comment]
What your deployment looks like exactly? Can you try using StreamingFast endpoint to determine where is the problem exactly?

**Comment by let4be** [comment]
I'm using a local deployment, BSC mainnet, latest firehose-ethereum for BSC chain, latest substreams release

**Comment by let4be** [comment]
Turns out it was related to firehose not being fully synced

**Comment by maoueh** [comment]
The latest released fixed a bug that was given the same behavior as you, so maybe latest release fixed the problem directly.
