### ISSUE TITLE
Make `substreams protogen` generate the actual Protobuf `mod.rs` file

### ISSUE THREAD

**Issue by maoueh** [streamingfast/substreams#161]
`protoc-gen-prost-crate` plugin can be used to generate the `mod.rs` file automatically which is handy because it reduce the amount of work needed to make Protobuf works.

We should add support in  `substreams protogen` to be default generate the `mod.rs` file. Now, this is going to be a breaking change because today we are not generating it and the newly generated one will not fit with the exact structure generated by the plugin.

So we will need to offer a way to disable that behavior for people that do not want that and still want to control the protobuf `mod.rs` generation.

- [x] Update `substreams protogen` to automatically generate `mod.rs` for protobuf definitions
- [x] Allow `substreams protogen --generate-mod-rs=false` flag (or a better flag name if you find one) when specified, fallback to how we were doing stuff before
- [x] Greatly enhanced documentation of `substreams protogen --help`
    - [x] One paragraph about the default behavior (generate Rust bindings + mod.rs)
    - [x] One paragraph about delegating to user if a `buf.gen.yaml` is found (already implemented but lacking documentation)
- [x] Modify `CHANGELOG` to but this new behavior in the release highlights as well as giving info about the new behavior and how developers can fallback to old behavior

**Comment by jubeless** [comment]
https://github.com/neoeinstein/protoc-gen-prost/blob/59f1c4baabab8202d9eb03b3c6d28644508d3fe2/protoc-gen-prost-crate/README.md
