### ISSUE TITLE
Last block of the range not included in the output

### ISSUE THREAD

**Issue by 0237h** [streamingfast/substreams#164]
When comparing data extracted using Firehose and Substreams (same endpoint, same block range), I realized that **substreams was skipping the last block of the range**.

#### Firehose output
```json
{"id": "0bebc2003b116a1803f87ea1c52778ba2ca5e3a3716c1dd782e4bf4b5056de1e", "number": 200000000}
{"id": "0bebc201a4e26758730db1dee6133227f034c32d0caa8d08b5d850547d9503c4", "number": 200000001}
{"id": "0bebc2029cc4777c4f65f46fb5219adb1e9f57e609859b8866024e325ac7be52", "number": 200000002}
{"id": "0bebc2036d13d39e33241bda8ccf3fc21ad7b45dcd53f6f6060aa23691d0798b", "number": 200000003}
...
{"id": "0bebc218190a17897394dffb8ba4210c070527d650e1200578510af25cf7701d", "number": 200000024}
{"id": "0bebc219b20f0f8282a3ceb05c6dc3c59390922df1b7340346e8320123750787", "number": 200000025}
```
#### Substreams output
```json
{"id": "0bebc2003b116a1803f87ea1c52778ba2ca5e3a3716c1dd782e4bf4b5056de1e", "number": 200000000}
{"id": "0bebc201a4e26758730db1dee6133227f034c32d0caa8d08b5d850547d9503c4", "number": 200000001}
{"id": "0bebc2029cc4777c4f65f46fb5219adb1e9f57e609859b8866024e325ac7be52", "number": 200000002}
{"id": "0bebc2036d13d39e33241bda8ccf3fc21ad7b45dcd53f6f6060aa23691d0798b", "number": 200000003}
...
{"id": "0bebc218190a17897394dffb8ba4210c070527d650e1200578510af25cf7701d", "number": 200000024}
```

The substreams CLI also hint that this might be a bug:
![image](https://user-images.githubusercontent.com/23462475/215799954-d54f6a73-5c6b-4cd4-b945-bc69c48ced17.png)

*PS: I use the tool I developed, [Pyfirehose](https://github.com/pinax-network/pyfirehose), to extract the block data from gRPC-enabled endpoints serving Firehose/Substreams in the background. It has also been reproduced using the substream CLI directly.*

**Comment by maoueh** [comment]
You are right, just tested on Ethereum and it's indeed not respecting the documentation. I think it's the right time to fix, will do.

**Comment by maoueh** [comment]
Might not be as easier as I thought, the stop block in the request is used to name some file on the disk, so could prove problematic.

**Comment by abourget** [comment]
Hmm.. can we just fix the doc string? Everywhere that stop block is exclusive if I recall correctly.. that's the assumption throughout the codebase.
Was the firehose inclusive of the stop block?

**Comment by 0237h** [comment]
Hi Alexandre,

> Was the firehose inclusive of the stop block?

To answer this question, yes Firehose currently includes the stop block (see log files in the first post).

It's a bit unpleasant at the moment to have Substreams and Firehose behave differently. My use case is that when splitting a large block range into smaller ones, I have to take this behavior into account for the last block of the sub-ranges (see [here](https://github.com/pinax-network/substreams_firehose/blob/main/substreams_firehose/block_extractors/common.py#L101)).

I think it makes sense for both to have the same behavior rather than just a docstring change (still, up to you to make the best call).

**Comment by maoueh** [comment]
@abourget Yeah I noticed that, that why changing it now it's much harder than anticipated, although possible. I'm pretty sure we have in mind to follow Firehose semantics about streaming, not quite sure what happened here when we did the implementation.

I'm also in favor of fixing it to align with Firehose.

**Comment by jubeless** [comment]
@Krow10 we won't be tackling this anytime soon. Re-open if necessary.
