### ISSUE TITLE
Nav. block increase speed over time when holding down `o/p`

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams#168]
For substreams with a lot of events, it could take quite a long time to iterate over data that is mid/end of your event stream.

When holding `o/p` to navigate to the next event, would it be possible to increase the interval after holding for X amount of seconds, this type of behavior is common when incrementing +1 counters, the first few seconds is +1 and after holding down, the counter increases the interval.

Suggestion/Example when holding down `o/p`:
- first 5 seconds: +1 events
- 5-10 seconds: +5 events
- +10 seconds: +10 events

**Comment by abourget** [comment]
What about a clickable interface?

**Comment by matthewdarwin** [comment]
I rarely think of clicking on things in a terminal ui.  `htop` does allow clicking on the column headers to sort, for example, so it is done.  Still want keyboard access probably.
