### ISSUE TITLE
Reverting undo segments is impossible with eth_call payloads from the past

### ISSUE THREAD

**Issue by abourget** [streamingfast/substreams#178]
## Problem

For this block sequence, where chain `b` gets finalized:

```
  9a -> 10a
     `> 10b -> 11b -> 12b
```

An `eth_call` is necessary at block `10a`. It is requested for that specific block ID from the RPC call.  We return the cursor for block `10a` and there is a disconnection.

Upon returning, the block 10a is not there anymore, in any archive node. It has been purged because it has not survived finality.
It is therefore impossible to re-execute `10a`, and re-obtain its payload as it was before.

## Solution

Tweak the response protocol to return only `undo` signals, and not the payload.

## Pushes the problem downstream

The sinks are the ones affected. They now need to keep track of the previous state that is still at risk of being reverted.

For the postgres and kv stores, this was already a problem:
* kv: since a key deletion would not provide the previous value, upon deleting a key, we needed to keep its previous value somewhere until finality.
* postgres: because incoming data is _field_-centric, even with incoming deltas for fields (which makes things much more complex anyway),  we need to keep track of the _other_ fields, when deleting a row. Also, keeping track of previous values in Substreams is extremely error-prone, if not useless when not used by the sink.

Downside: it means that stateless substreams consumers now need to keep state to handle undos, if they care about such things. However, any process that cares about undoing anything needs to track the thing to be undone, and that is already some state. So, I'm left without examples where this is an actual problem.

## Help sinks handle state

 It would be beneficial to have a signal when certain blocks pass finality. This would help the sink purge the state that reaches finality.

**Comment by jubeless** [comment]
merged with issue: https://github.com/streamingfast/substreams/issues/199
