### ISSUE TITLE
throw error/warning when `import` (typo) used in manifest

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams#179]
Throw error or warning when `import` used in manifest

```yaml
import:
  pkg: <URL>
```
Found myself trying to troubleshoot why the import function didn't decode my spkg

The issue was it was ignoring `import` since the syntax is `imports` (with an s)

This is an easy typo that many devs will encounter, if we can inform the user of such error/warning when executing `substreams pack`

**Comment by YaroShkvorets** [comment]
Should throw an error on any unknown fields in the manifest probably.
The other day I used `initial_block` instead of `initialBlock` and couldn't figure out what was going on.
