### ISSUE TITLE
Support negative start block

### ISSUE THREAD

**Issue by YaroShkvorets** [streamingfast/substreams#186]
Firehose supports negative start block if I want to stream relative to head block.
But substreams does not. [Says TODO here](https://github.com/streamingfast/substreams/blob/5d9eadeecd0afb410a11c2b3078fe999c5f2c296/pb/sf/substreams/v1/substreams.go#L59).

Possible use case: say I have a module that emits some rare events that I want to push to discord channel for example. I would want to start streaming it from head block.

**Comment by sduchesneau** [comment]
👍 
fixed here: 82357e1e27cd540755fb0c2b10e30c43c1c6d0a7
