### ISSUE TITLE
Subgraph syncing "reading file existence" error

### ISSUE THREAD

**Issue by YaroShkvorets** [streamingfast/substreams#197]
Another interesting error for @sduchesneau 
First time seeing it, seems to recover from it, so probably no big deal.

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/29608734/226956657-f18804a0-831d-416a-932a-91a946dc4b0f.png">

Text:
`
An error occurred while streaming blocks: status: Internal, message: "reading file existence: Get \"https://storage.googleapis.com/storage/v1/b/dfuseio-global-blocks-uscentral/o/eth-mainnet%2Fv4%2F0016883700.dbin.zst?alt=json&prettyPrint=false&projection=full&userProject=dfuseio-global\": stream error: stream ID 2939; INTERNAL_ERROR; received from peer", details: [], metadata: MetadataMap { headers: {} }, component: SubstreamsBlockStream
`

**Comment by sduchesneau** [comment]
It is a transient error, it can be ignored.

It is not good that the details of the error bubble up to the user (it leaks infrastructure details..), so I will change that. But if the storage starts to fail, it is the wanted behavior that it fails the request (and not silently retry..)

**Comment by sduchesneau** [comment]
Closing as this is the correct behavior when the storage backend gives an error and will be fixed automatically when the storage works again.
The other errors (old cursor...) are discussed thoroughly here https://github.com/streamingfast/substreams/issues/196
