### ISSUE TITLE
Substreams: High Level overview

### ISSUE THREAD

**Issue by jubeless** [streamingfast/substreams#20]
What I feel is missing is some way to grasp what Substreams are, super high levels.

**Comment by seanmooretechwriter** [comment]
This was an issue in Firehose as well. This should be addressed as I go through each page during updates. I'll leave this task open to return to for a review once the majority of major updates have been completed.

**Comment by seanmooretechwriter** [comment]
I've made some updates to the Substreams main/home page in docs. I think these help. Even with the changes I still feel it's probably imperative to answer the questions:

What is substreams? — in one simple sentence
How do I use a substream? — in one simple sentence
Why do I need substreams? — in one simple sentence

I'll need some input on these. If someone wants to take a stab I can massage whatever you come up with. These are core questions that I don't feel are immediately or easily answered anywhere in the current Substreams material including docs and all the repos.

**Comment by seanmooretechwriter** [comment]
Here are a couple of initial passes of what I think we need to come up with for both products.

What is Firehose? — Firehose substantially increases the speed of indexing and the synchronization of blockchain data.

What is Substreams? — Substreams work in conjunction with Firehose and Subgraphs to massively increase query speeds and breadth of blockchain data.

Please feel free to correct these and add to them. But do remember we need super-simple here. We need to distill what these products are and explain it concisely and simply to people.

**Comment by seanmooretechwriter** [comment]
Substreams main landing page and subsequent intro pages all revised and updated for additional clarity and to help create a bridge for new people. This will hopefully help people get to the point of knowing nothing about the product to gaining a basic understanding of what it is, what it's for and what it's not. This should enable understanding the more complex topics involved with Substresms later.

Please review for accuracy and anything else and feel free to provide feedback. 

Thanks!

**Comment by seanmooretechwriter** [comment]
Haven't heard back. Closing this task.
