### ISSUE TITLE
gui/run: target block when start block negative

### ISSUE THREAD

**Issue by YaroShkvorets** [streamingfast/substreams#216]
When running with negative block, uint64 underflows and makes no sense:

<img width="562" alt="image" src="https://github.com/streamingfast/substreams/assets/29608734/bdb3a2d2-64cf-40bf-9042-6422f49ab5c6">

<img width="524" alt="image" src="https://github.com/streamingfast/substreams/assets/29608734/8e591908-4922-49a9-8a1b-be4374e7854f">

**Comment by sduchesneau** [comment]
Ok, the substreams client does not know the actual "resolved target block"... we will have to send back this information from the server at the beginning, maybe in the Response_Session message... It can't be fixed only in the client.

**Comment by sduchesneau** [comment]
^ fixed in GUI, wait for deployment of updated server to see the fix in action. It will now show '0' until server is updated.
