### ISSUE TITLE
Add support to run a substream defined as part of a subgraph

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/substreams#218]
So that indexers in The Graph community can easily test that a substream-based subgraph is working, add new options to `substreams run` to  pull the .spkg information out of a subgraph defined on ipfs.

eg: `substreams run QmeWyu8pzV3zViL5nz813NxKSab7REh9qJBivjzkCzE9Vw`

**Comment by matsuro-hadouken** [comment]
This will be awesome

**Comment by sduchesneau** [comment]
Now supported, with `substreams run ipfs://QmeWyu8pzV3zViL5nz813NxKSab7REh9qJBivjzkCzE9Vw` or `substreams gui ipfs://...`

New Global Flags:
```
      --ipfs-timeout duration   IPFS timeout when resolving substreams-based subgraphs as manifest (default 10s)
      --ipfs-url string         IPFS endpoint to resolve substreams-based subgraphs as manifest (default "https://ipfs.network.thegraph.com")
```
