### ISSUE TITLE
invalid character `'.'` in crate name: `substreams.yaml`

### ISSUE THREAD

**Issue by gusinacio** [streamingfast/substreams#220]
I currently running the [Quickstart](https://substreams.streamingfast.io/getting-started/quickstart) of the substreams documentation and it fails the build part with:

```
.
.
. 
   Compiling impl-serde v0.3.2
   Compiling ethbloom v0.12.1
   Compiling impl-codec v0.6.0
   Compiling primitive-types v0.11.1
   Compiling ethereum-types v0.13.1
   Compiling ethabi v17.2.0
   Compiling substreams-ethereum-core v0.9.1
   Compiling substreams-ethereum-abigen v0.9.1
   Compiling substreams-ethereum-derive v0.9.1
   Compiling substreams-ethereum v0.9.1
   Compiling substreams-ethereum-quickstart v1.0.0 (/home/gustavo/tutorial-substream)
error: invalid character `'.'` in crate name: `substreams.yaml`

error: could not compile `substreams-ethereum-quickstart` due to previous error
```

After looking at other projects like [substreams-uniswap-v3](https://github.com/streamingfast/substreams-uniswap-v3) and [substreams-template](https://github.com/streamingfast/substreams-template), it looks like the crate name in `[lib]` ins't necessary. I suggest removing/changing it in the documentation.

**Comment by maoueh** [comment]
The `lib` is indeed not necessary, but it defines the final filename of the produced `.wasm`, it's easier to define to be `substreams` all the time.

I think it was replaced by mistake when doing a search/replace within the documentation file. Using `name = "substreams"` was the right thing to put.
