### ISSUE TITLE
Substreams CLI to allow comma character to be used as params value

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams#227]
Now `,` comma are not allowed to be used in Substreams CLI params?

> Note: Injecting "," in params does work directly with Substreams, this issue is only related to Substreams CLI.

Ref: https://github.com/streamingfast/substreams/issues/221

I doubt this is the correct behavior since the use of comma is quite a common character to signal a delimiter.

Each module param should allow any characters.

The following should be allowed:

**Single Module param**
` -p module1=valA`

**Single Module param with comma**
` -p module1=valA,valB`

**Multi Module param**
`-p module1=valA -p module2=valX&valY`

**Multi Module with commas**
`-p module1=valA,valB -p module2=valX&valY,valZ`

## Usecase

```
substreams run map_transfers -s -1 -p map_transfers="to=swap.defi&symcode=EOS,USDT"
```

**Comment by maoueh** [comment]
@emiliocramer

**Comment by emiliocramer** [comment]
Hey,
I just made this change for you at this commit 0e6b74b99d2ffa6b9b049950ea740097f9bd0a79.  You can see the changelog change here https://github.com/streamingfast/substreams/blob/develop/docs/release-notes/change-log.md?plain=1#L33.
