### ISSUE TITLE
GUI params empty

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams#228]
## ✅ Works using `substreams run`

```
substreams run map_transfers -s -1 -p map_transfers="to=swap.defi&symcode=USDT"

----------- BLOCK #312,541,107 (12a0ffb3d62ec7ddedcba0043096fa3f8267af550c631942077cc0752311389d) ---------------
map_transfers: log: params: "to=swap.defi&symcode=USDT"
map_transfers: log: filter: "from" {}
map_transfers: log: filter: "to" {"swap.defi"}
map_transfers: log: filter: "symcode" {"USDT"}
map_transfers: log: filter: "contract" {}
map_transfers: log: filter: "to_or_from" {}
```

## ❌  empty using `substreams gui`

```
substreams gui map_transfers -s -1 -p map_transfers="to=swap.defi&symcode=USDT"
```

<img width="528" alt="image" src="https://github.com/streamingfast/substreams/assets/550895/50e10c92-b34e-4da7-8ea9-8809e84a6084">

**Comment by sduchesneau** [comment]
Hey Denis, this feature has been added since commit 1e07b59f8bed536e6c8ec756644448207ef279c5
 (May 23)

it is part of release v1.1.4, can you try again with this version ? 
It works for me ™️

**Comment by DenisCarriere** [comment]
@sduchesneau still doesn't show any `params` when using `gui`

## Release used

```
$ substreams --version                                                                                                 
substreams version dev (Commit d89602d, Built 2023-06-02T14:33:34Z)
```

## Example

### ❌ GUI

> substreams gui -e eos.firehose.eosnation.io:9001 https://github.com/pinax-network/substreams/releases/download/eosio.token-v0.12.1/eosio-token-v0.12.1.spkg map_transfers -s -1 -p map_transfers="to=swap.defi&symcode=EOS,USDT"

<img width="339" alt="image" src="https://github.com/streamingfast/substreams/assets/550895/54d2b793-7d9c-4e53-be8e-32792251ea01">


### ✅ Run

> substreams run -e eos.firehose.eosnation.io:9001 https://github.com/pinax-network/substreams/releases/download/eosio.token-v0.12.1/eosio-token-v0.12.1.spkg map_transfers -s -1 -p map_transfers="to=swap.defi&symcode=EOS,USDT"

<img width="457" alt="image" src="https://github.com/streamingfast/substreams/assets/550895/42338ae5-3625-487e-a762-445add0c470a">

**Comment by ghardin1314** [comment]
also having this same issue

**Comment by maoueh** [comment]
Fixed by https://github.com/streamingfast/substreams/commit/bb09e70b6f3067feb7796d2e10ecd958c5a1b918, will be included in next release, probably early next week.
