### ISSUE TITLE
`alpha init`: snake case with numbers

### ISSUE THREAD

**Issue by YaroShkvorets** [streamingfast/substreams#239]
`substreams alpha init` generates wrong event parameter name when that parameter contains a number [here](https://github.com/streamingfast/substreams/blob/2acfbab847a318e96548a8b5e93ad20196ff046b/codegen/templates/ethereum_project.go#L178)

I.e. `myToken0` becomes `my_token_0` name instead of `my_token0` as expected by `substreams_ethereum::Abigen`

Looks like a bug in upstream library: https://github.com/iancoleman/strcase/issues/22

Contract address to reproduce: 1f98431c8ad98523631ae4a59f267346ea31f984

**Comment by maoueh** [comment]
Ok thanks, I think we will need to add small check after generating the name to see if it matches some pattern that needs to be flatten to respect Rust generated code.

**Comment by YaroShkvorets** [comment]
I didn't check but maybe this library better matches Abigen behaviour: https://pkg.go.dev/github.com/huandu/xstrings?utm_source=godoc#ToSnakeCase

**Comment by maoueh** [comment]
Seems it does: https://go.dev/play/p/a0qiFkpIRcu, I'll think about switching to it
