### ISSUE TITLE
Sustreams: Change History Review

### ISSUE THREAD

**Issue by jubeless** [streamingfast/substreams#24]
Review the change history of the Substreams repository https://github.com/streamingfast/substreams
and ask the team what's new, find a way to present the new things in the change-log, sync the GitHub releases page with what's new.

Let's plan together how we could best communicate what is new. Our release process is not so strictly defined, so we can figure out what's best together.

**Comment by maoueh** [comment]
We are manually maintaining the change log for now, every developers should maintain it and contributing must be asked to add a changelog entry.

I think it a good enough system like this. Let's re-open if we still want to work further on this.
