### ISSUE TITLE
`uint32` as value 0 does not show up in GUI

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams#240]
Most likely just GUI display issue, the data does show up as "0" (which is not null value)

```proto
message TransferEvent {
  // trace information
  string transaction = 5;
  int32 status = 6;
  uint32 block_index = 7;
}
```

<img width="1076" alt="Screenshot 2023-06-25 at 9 53 52 PM" src="https://github.com/streamingfast/substreams/assets/550895/89ed6975-9ca9-41ab-aea7-ce9f88621cd0">

```rust
    for log in block.logs() {
        log::debug!("block index {}", log.log.block_index);
```

<img width="1076" alt="Screenshot 2023-06-25 at 9 55 00 PM" src="https://github.com/streamingfast/substreams/assets/550895/5fbcf50a-e4b3-4283-8376-8c4c8886fd2b">

**Comment by maoueh** [comment]
This is a quirks of Go JSON renderer and generated code which makes field with default value (`0`, `""`, `nil`, etc.) to not render.

Note sure how involving this will be to workaround.

**Comment by YaroShkvorets** [comment]
Had the same problem.
Dove a bit into it. 
This fix worked for me: https://github.com/streamingfast/substreams/pull/242

**Comment by DenisCarriere** [comment]
Perfect, confirms this works 🙇 @YaroShkvorets thanks

<img width="838" alt="image" src="https://github.com/streamingfast/substreams/assets/550895/1a98cf47-9446-415c-ae79-749cd845bd05">
