### ISSUE TITLE
`alpha init`: set `initialBlock`

### ISSUE THREAD

**Issue by YaroShkvorets** [streamingfast/substreams#247]
Generator could pull contract creation block from etherscan along with ABI and set `initialBlock` in `substreams.yaml` instead of using `0`: https://github.com/streamingfast/substreams/blob/faed57f78173422335427092dbe5ecb6b1ae82de/codegen/templates/ethereum/substreams.yaml#L20

**Comment by maoueh** [comment]
@YaroShkvorets In your PR that fixes an issue, add in the PR's description `Fixes #<bug>`, GitHub will auto-close the issue on merge.
