### ISSUE TITLE
Substreams: Rust API

### ISSUE THREAD

**Issue by jubeless** [streamingfast/substreams#26]
Review the Rust APIs section, and its interaction with the documentation living in the docs.rs website. https://substreams.streamingfast.io/reference-and-specs/rust-api

Perhaps the links should point to the docs directly, instead of crates.io, (or in a table view with a direct link to the docs).
The links should be without version, so they are directed to the latest version: https://docs.rs/substreams-ethereum and https://docs.rs/substreams ...

**Comment by seanmooretechwriter** [comment]
Need additional information and help from the dev team to resolve this.
