### ISSUE TITLE
Stacktraces on Solana

### ISSUE THREAD

**Issue by abourget** [streamingfast/substreams#263]
It seems stacktraces don't bubble up properly in Solana Substreams. /cc @billettc

**Comment by maoueh** [comment]
We indeed only receives the last line in the returned error message. Good news, the message contains the correct source information which means symbol resolution seems to work on that aspect.

Getting the full stacktrace could be a good addition, however, I discussed with Charles and even if we added that, it wouldn't solve his current problem. 

His problem is that he gets a `Result<..., Error>` from a library and he would like to know where this `Error` have been generated, this is not something having the full stack trace would have solved as the stack trace would have need to be attached by the one who generate the `Err(...)` initially.

**Comment by abourget** [comment]
Can we close this then @billettc @maoueh ?

**Comment by maoueh** [comment]
Still feels like a good addition, you decide.

**Comment by maoueh** [comment]
Right now we display a single line of trace when an error happen, the location of the error. Turn this into printing the full stacktrace of execution at point of failure.

**Comment by abourget** [comment]
But the intrinsic for reporting does report the full stack, doesn't it ? Is it the same on Ethereum? I recall seeing full stack traces. Is that Solana specific?!
