### ISSUE TITLE
caching not working on substreams with no stores

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/substreams#275]
I am running `substreams run --production-mode --plaintext -e localhost:9000 ipfs://qmt99y8q2xvxcajkjp5iyfy1wakegkw4svzxcusalcvxhq/ graph_out -s 6800000 -t 6810000 | grep @block` and I can see that each time I run it, it kicks off the tier2 workers and updates the cache file  (this is Denis' ERC20 substream)

```
$ rclone lsl march:eth-sf-v4-substreams-state/dc04d620def87b6205afe1db9158d3d3fdc37e3c/outputs/0006805000-0006806000.output.zst
  4837381 2023-07-31 17:48:48.000000000 0006805000-0006806000.output.zst
[re-run above sink, output is changed]
$ rclone lsl march:eth-sf-v4-substreams-state/dc04d620def87b6205afe1db9158d3d3fdc37e3c/outputs/0006805000-0006806000.output.zst
  4839797 2023-07-31 17:49:49.000000000 0006805000-0006806000.output.zst
```

I ran this a few times, the output file size is not the same each time.  But really since it is already cached, why does it need to re-generate it at all.  (localhost:9000 is ethereum tier1 grpc).  I can see lots of load on the tier2 nodes and i/o on the s3 bucket, so it appears to re-generate every time.

**Comment by jubeless** [comment]
This is not implemented we are tracking that separately.
