### ISSUE TITLE
StreamingFast: ReadME

### ISSUE THREAD

**Issue by jubeless** [streamingfast/substreams#28]
Remove the second paragraph of "Features", touting Search and Lifecycle as products.
Remove all "Top-tier products" in the Overview section.
Update "Protocols", to include Solana, NEAR. Start with Ethereum. Also include as "Contributed by third-parties", the ones by Figment (https://github.com/figment-networks/firehose-cosmos which includes the Cosmos Hub and Osmosis network). Remove the EOSIO one from the Protocols list.
Links to Docs should point to: the FIrehose docs (firehose.streamingfast.io) and Substreams (to substreams.streamingfast.io)
Remove the "Common interfaces" section.
Grab Google's CODE_OF_CONDUCT doc from somewhere, and tweak it to reflect our name, and put it in this repository. When we have a code of conduct linked somewhere, we can ask GitBook for a free "open-source project" license.
Change the "about" and "website" section of the GitHub repository, to point to streamingfast.io and our latest company name.

**Comment by seanmooretechwriter** [comment]
I'm not sure what repo this was in regard to for the README file.

**Comment by maoueh** [comment]
Closing, the issue seems quite outdated and talks about what it seems Firehose documentation, should probably be logged else where actually or maybe it's already done.
