### ISSUE TITLE
Firenear with Substreams v1.1.12 generates error messages in log

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/substreams#294]
From tier1 and tier2 on firenear after latest upgrade to substreams 1.1.12

```
(firenear.metrics.emitter) failed to emit event {"error": "rpc error: code = Internal desc = grpc: error unmarshalling request: string field contains invalid UTF-8"}
``

**Comment by maoueh** [comment]
@colindickson Can you check tomorrow if we have those in your own deployment?

**Comment by matthewdarwin** [comment]
Also happens on `fireeth`

```
 (fireeth.metrics.emitter) failed to emit event {"error": "rpc error: code = Internal desc = grpc: error unmarshalling request: string field contains invalid UTF-8"}
```

**Comment by matthewdarwin** [comment]
Example test case:

```
substreams gui -e neartest.substreams.pinax.network:9000 https://github.com/pinax-network/substreams/releases/download/common-v0.6.0/common-v0.6.0.spkg kv_out -s 42376888 --production-mode
```

**Comment by colindickson** [comment]
@matthewdarwin i am running the substreams against our near testnet endpoint and i am not encountering the error.    what are you using for your `--common-metering-plugin`? can you check your logs on there?

**Comment by fschoell** [comment]
our metering plugin wasn't updated yet to read the metering events as batches, working now
