### ISSUE TITLE
Network config override for Substreams manifests

### ISSUE THREAD

**Issue by jubeless** [streamingfast/substreams#309]
```
SUBSTREAMS_ENDPOINTS_CONFIG_POLYGON=polygonl.friend.com:443
SUBSTREAMS_ENDPOINTS_CONFIG_MAINNET=ethmainn.friend.com:443
```
To support:
`substreams run myfile.polygon.yaml`
and:
`substreams run myfile.yaml`  // where network is `mainnet`
`myfile.polygon.yaml`:
```yaml
network: polygon
#network: mumbai
#network: goerli
#network: goerli
#network: eip1544
```
Align with: https://thegraph.com/docs/en/developing/supported-networks/
1. SUBSTREAMS_ENDPOINTS_CONFIG_\[network\] and defined in the manifest. (this is what needs implementing)
2. SUBSTREAMS_ENDPOINT viper-based config
3. -e value
4. default `-e` value (remove the default value, issue a deprecation notice)
- Error: missing endpoint, specify -e or `SUBSTREAMS_ENDPOINTS_CONFIG_[network]` as defined in `network` field of the Substreams manifest.

**Comment by sduchesneau** [comment]
* Substreams will have a hardcoded map of 'network -> endpoint' to use if the environment variables are not used. It will point to all streamingfast's endpoints, or Pinax for the ones that we don't support but they do (ex: antelope)
* This hardcoded map will come with a "TODO" comment saying that this is temporary until we have something "distributed" (like, the gateway advertising available endpoints or whatever)
* If a substreams manifest does not specify the 'Network', the default is to consider it to be `mainnet`.
* the `-e` flag always overrides this whole mechanism

The idea is also that the 'subservicesd' component, where we deploy, will use those values...
