### ISSUE TITLE
Move `substreams alpha init` to `substreams init`

### ISSUE THREAD

**Issue by jubeless** [streamingfast/substreams#319]
Take `substreams alpha init` out of alpha.

**Comment by Eduard-Voiculescu** [comment]
Done in branch `feature/alpha-init-integration`

**Comment by maoueh** [comment]
Re-opening until merged in `develop` (add in one of your commit `Closes #319` and it will auto-close when merged).

**Comment by abourget** [comment]
Was this not merged? :)

**Comment by Eduard-Voiculescu** [comment]
Yep, this is done.
