### ISSUE TITLE
Do Substreams-powered subgraphs support Solana? 

### ISSUE THREAD

**Issue by patricktst** [streamingfast/substreams#356]
Do Substreams-powered subgraphs support Solana? I try the example: [GitHub - graphprotocol/graph-tooling: Monorepo for various tools used by subgraph developers.](https://github.com/graphprotocol/graph-tooling), It is Ethereum blockchain

**Comment by enoldev** [comment]
Hello! It's currently not supported.

You can find more information on this page https://thegraph.com/docs/en/developing/supported-networks/
