### ISSUE TITLE
Use options WithWalltime, WithSysWalltime, WithNanotime, WithSysNanotime, WithNanosleep, WithSysNanosleep and WithRandSource to prevent any randomness in substreams executions

### ISSUE THREAD

**Issue by billettc** [streamingfast/substreams#372]

**Comment by colindickson** [comment]
WithRandSource does not seem to behave as expected.  

1) documentation says: 	`WithRandSource configures a source of random bytes. Defaults to return a deterministic source. You might override this with crypto/rand.Reader`, however this does not seem to hold

2) when using a static source, the output is still different between runs.

need to investigate further

**Comment by colindickson** [comment]
default walltime and time methods already do desired behaviour.  (base time of 2022-01-01 00:00:00)

**Comment by colindickson** [comment]
done
