### ISSUE TITLE
Importance of specifying protobuf files in `substreams.yaml` manifest 

### ISSUE THREAD

**Issue by catalyst17** [streamingfast/substreams#377]
Me and @fubhy have discovered an issue that was first thought to be a bug of just [substreams-js](https://github.com/substreams-js/substreams-js) library but after some research it was concluded to be a problem of `SPKG` generation by the `substreams` CLI.

The issue is that as soon as any protobuf files are specified in the manifest and those files actually do the import of the ones that are not specified there or are specified later on on the lines below, running that package will result in errors like this:
```
Error: building message descriptors: couldn't convert, should do this check much earlier: no such file: "nitro_rollup.proto"
```
or like this:
```
invalid FieldDescriptorProto: type_name .eth.blocktorch.v1.NitroRollup not found"
```

One of the solutions found is to not specify any files at all, while just specifying the path, like this:
```
protobuf:
  files:
  importPaths:
    - ./proto
```

I'm not sure what would be the best fix here since I do not have that deep experience working with protobufs, but as a frequent Substreams user I'd at least suggest adding more information/instruction in [this section](https://substreams.streamingfast.io/developers-guide/creating-your-manifest#protobuf.files) of the docs.

More details and the prior discussion can be found in https://github.com/substreams-js/substreams-js/issues/54

**Comment by sduchesneau** [comment]
When creating an spkg file now, the protobuf will be ordered topologically, so that protobuf files are always added after their dependencies.

**Comment by maoueh** [comment]
Closing as this should be fixed everywhere now (Substreams CLI and in the library).

Re-open if you any further issue.
