### ISSUE TITLE
How to install substreams CLI for ubuntu

### ISSUE THREAD

**Issue by ghost** [streamingfast/substreams#386]
I try to install by **[docs](https://substreams.streamingfast.io/documentation/consume/installing-the-cli#installation-from-source)**
But it's not run on ubuntu.

**Comment by matthewdarwin** [comment]
Please provide details of exactly the steps you are taking and what is the error messages.
Also you might want to start a discussion in the StreamingFast discord channel instead of using github issues to do troubleshooting.
