### ISSUE TITLE
Create an blockIndex module that replicates what we have in firehose for ethereum (match logs and calls)

### ISSUE THREAD

**Issue by sduchesneau** [streamingfast/substreams#413]
# Dependencies

#410 #411 #412

# TODO

- [ ] The module should simply be an index that outputs the keys like: 

  * event signature: `evsig:deadbeef` 
  * event address: `evaddr:123456789...`
  * call method: `callsig:deadbeef`
  * call address: `calladdr:123456789...`

- [ ] That module should be published to substreams.dev

**Comment by ArnaudBger** [comment]
Waiting for review/testing 

https://github.com/streamingfast/substreams-ethereum-indexes

**Comment by sduchesneau** [comment]
shipped, eth-common in https://github.com/streamingfast/substreams-ethereum-indexes
