### ISSUE TITLE
When importing module using substreams.yaml, substreams is looking for binary in the incorrect folder

### ISSUE THREAD

**Issue by this-username-is-taken** [streamingfast/substreams#46]
Example:

I have two substreams (erc721 and uniswap) with the following folder structure:
```
- erc721
  - substreams.yaml
  - target/.../substreams_erc721.wasm
- uniswap
  - substreams.yaml
  - target/.../substreams_uniswap.wasm
```

When I import the `erc721` substream in `uniswap`'s substreams.yaml, and build, I see the following error:

```
~/go/bin/substreams protogen ./substreams.yaml --exclude-paths="sf/ethereum,sf/substreams,google"
Error: reading manifest "./substreams.yaml": error loading imports: importing "../erc721/substreams.yaml": failed to convert manifest to pkg: failed to read source code "./target/wasm32-unknown-unknown/release/substreams_erc721.wasm": open ./target/wasm32-unknown-unknown/release/substreams_erc721.wasm: no such file or directory
```

However, if I copy `erc721/target/.../substreams_erc721.wasm` to under `uniswap/target/.../substreams_erc721.wasm` the error goes away. I think `substreams` is looking for the binary in the main substreams.yaml instead of the imported substreams.yaml.

See https://github.com/messari/substreams/blob/2ef4b9278c8a6d372c48e1df8c4be869081f481b/uniswap-v2/substreams.yaml#L8 or https://github.com/messari/substreams/commit/2ef4b9278c8a6d372c48e1df8c4be869081f481b

**Comment by maoueh** [comment]
Fixed by e36a3f87ec38699868b6befe8573bbde09d694cc
