### ISSUE TITLE
Fix Substreams upload

### ISSUE THREAD

**Issue by JeremyGarcini** [streamingfast/substreams#472]
Redirection issue when attempting to publish from the streamingfast/cosmos substream or other. Upon hitting the "Upload" button, the system incorrectly redirects to the URL https://substreams.dev/streamingfast/cosmos/streamingfast/cosmos/v0.1.5 instead of the expected path. 

Steps to Reproduce:

Navigate to the **streamingfast/cosmos** substream.
- Click on "Upload".
- Observe the redirection to an incorrect URL.
 
**Expected Result:**
- The correct redirection should only append the version number to the current path, e.g., https://substreams.dev/streamingfast/cosmos/v0.1.5.

**Actual Result:**
The URL is duplicated before appending the version, leading to https://substreams.dev/streamingfast/cosmos/streamingfast/cosmos/v0.1.5.

**Comment by abourget** [comment]
Let's also publish this if possibel: https://github.com/decentraland/decentraland-substreams/releases/tag/1.6.0
It's their main thing and it's not published.

**Comment by JeremyGarcini** [comment]
@MavericksFive

**Comment by ArnaudBger** [comment]
Fixed
