### ISSUE TITLE
Update IPFS client to supported code

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/substreams#509]
https://github.com/streamingfast/substreams/blob/a46ef84d1d04c16503ff7da9dbfe23ad17a3d50e/manifest/reader.go#L16C8-L16C35 references the obsolete https://github.com/ipfs/go-ipfs-api

It points to this issue https://github.com/ipfs/kubo/issues/9124 to find the latest code

Please update to latest.

**Comment by sduchesneau** [comment]
fixed in https://github.com/streamingfast/substreams/commit/090fff92fbb0a74da2fdf77ea8429270b4092352, 
release v1.9.3

kubo is a huge complex machine that pulls TONS of dependencies and breaks compatibility with some older modules, using a simple http.Get fixes the issue.
