### ISSUE TITLE
Stream Blocks always get stuck on a certain block and don't push new BlockScopedData data？

### ISSUE THREAD

**Issue by override-coder** [streamingfast/substreams#562]
Using Stream Blocks, it always gets stuck on a certain block and does not push new BlockScopedData data. It keeps returning progress data. Can anyone help explain the reason behind this?

**Comment by maoueh** [comment]
Hey @override-coder, see https://github.com/streamingfast/substreams-sink/issues/5#issuecomment-2512400199 where I'm given reasons why there could be delays in block streams in production mode for historical blocks.

Let's continue the discussion there or over Discord.
