### ISSUE TITLE
Start upcoming documentation of development vs production mode and the implications for the user

### ISSUE THREAD

**Issue by maoueh** [streamingfast/substreams#67]
The mode will have an impact on how a Substreams backend will behave. For a quick example, in developments mode, logs will now always be visible and forward processing will not be activated. I imagine this will have implications at different level in the documentation. For this, I will ask Alex to have a session with you to describe you the features and the implications and you will be able to gather the information. Maybe even record the Zoom call for later references for you.

**Comment by maoueh** [comment]
@abourget is assigned to help you generate the initial content of this mode. I think we have even some material written that could be used (very raw material, kind of quick data points about the differences for development vs production).

**Comment by seanmooretechwriter** [comment]
This is the next item in the queue I'll be addressing. Where is the existing initial content located? I'll begin reviewing it to get more context.

Can we develop a loose outline to help provide a high-level overview of the content that will need to be created? Something extending from the following:

**Development Mode**
  - Logs
  - Forward processing (not available)
  - sub-topic 3

**Production Mode**
  - sub-topic 1
  - sub-topic 2
  - sub-topic 3

**User Implications**
  - sub-topic 1
  - sub-topic 2
  - sub-topic 3
  - 
What else?

**Comment by seanmooretechwriter** [comment]
Initial draft outline added to the Running Substreams page of the docs. PR submitted here: https://github.com/streamingfast/substreams/pull/103
