### ISSUE TITLE
Investigate missing `.kv` file reported on Discord

### ISSUE THREAD

**Issue by maoueh** [streamingfast/substreams#77]
It was reported in Discord by Jimmy Dorsey that sometimes, using recent enough `develop` branch, he hit problem related to a `.kv` file missing.

Error similar to this one (it's not the exact one reported, but he replied on this error saying he was experiencing the same:

```
An error occurred while streaming blocks: Status { code: Internal, message: "error building pipeline: failed setup request: backrprocess run: scheduler run: process job result: worker ended in error: receiving stream resp: rpc error: code = Internal desc = error building pipeline: faile to setup backprocessings: load full store: load full store store_uniqs at 0014890000-0013885625.kv: not found", source: None },
```

See https://discord.com/channels/666749063386890256/1052699094545616926 for 2 `.spkg` that should reproduce the problem, it's not clear what exactly is causing it, expectation is that running it with forward processing which triggers the bug at some point.

This needs to be investigated.

**Comment by colindickson** [comment]
do we know which version of the server he was running against at the time?   unstable or stable?

**Comment by sduchesneau** [comment]
I can reproduce locally. I'll write a test to cover this so we can fix without risk of regression.

**Comment by sduchesneau** [comment]
after a few tries, I cannot reproduce it anymore, more digging is needed..

**Comment by maoueh** [comment]
Closing until someone (or us) report back
