### ISSUE TITLE
Perform actual release (Substreams, Firehose Ethereum, others?)

### ISSUE THREAD

**Issue by maoueh** [streamingfast/substreams#95]
This is the task list I see for when we are going to do the release:

- [x] Release https://github.com/streamingfast/substreams, let's bump it to 0.1.0
    - Ensure the documentation is up to date (cross-check with Sean)
    - Ensure the release on GitHub contains the full changelog (also ensure we publish as draft on GitHub, and after set the changelog and then publish officially, this is to ensure the email people receive has the full details of the release notes)
- [x] Move `substreams` `master` branch to point to `0.1.0` tag
- [x] Release https://github.com/streamingfast/firehose-ethereum, let's bump it to 1.3.0
    - Don't forget to build all Docker images with prebuilt Geth binaries also on 1.3.0, see README in the repo for details on how to perform this
- [x] Move `firehose-ethereum` `master` branch to point to 1.3.0

**Comment by sduchesneau** [comment]
I'm deploying develop to `unstable` so we run some tests before `62d486d` becomes the target "code" tag...

**Comment by maoueh** [comment]
Great
