### ISSUE TITLE
Update `substreams` README.md in repo a bit

### ISSUE THREAD

**Issue by maoueh** [streamingfast/substreams#99]
https://github.com/streamingfast/substreams#tooling Really wondering why that “Tooling” section  made it to the top-level README.md :slightly_smiling_face: Clearly doesn’t belong there. Perhaps its own section under “CLI Reference”? Maybe we give a few hints at what the tools sub-commands do.

**Comment by seanmooretechwriter** [comment]
Removed the Tooling section. The content is backed up in the comment I left when committing the change.
